/**
 * PEXPACKS ADMIN — UNIFIED TAILWIND STYLES DICTIONARY
 * 100% Token & Visual Parity replacement for app/admin/admin.module.css
 * Generated from master admin stylesheet (2,473 lines)
 */

export interface AdminStylesDictionary {
  [key: string]: string;
}

const rawStyles: AdminStylesDictionary = {
  "adminContainer": "w-full max-w-full [margin-inline:auto]",
  "headerSection": "[margin-bottom:clamp(28px,_4vw,_44px)]",
  "pageTitle": "m-0 text-[clamp(22px,3vw,28px)] font-bold text-[var(--a-text)] tracking-[-0.02em]",
  "pageSubtitle": "[margin-top:10px] [margin-bottom:0] text-[13px] leading-[1.5] text-[var(--a-text-3)]",
  "count": "text-[12px] font-semibold text-[var(--a-text-4)] [margin-left:8px]",
  "stack": "flex flex-col gap-[18px]",
  "stackRow": "flex items-center gap-[12px] flex-wrap",
  "primaryButton": "inline-flex items-center justify-center gap-[8px] h-[var(--a-btn-h,40px)] p-[0_20px] border border-[rgba(16,185,129,0.5)] rounded-[var(--a-btn-radius,8px)] bg-[#10b981] [background:linear-gradient(135deg,_#10b981_0%,_#059669_100%)] text-white [font-family:inherit] text-[14px] font-bold cursor-pointer no-underline [box-shadow:0_2px_10px_rgba(16,_185,_129,_0.25)] [transition:all_var(--a-transition,_150ms_ease)]",
  "secondaryButton": "inline-flex items-center justify-center gap-[8px] h-[var(--a-btn-h,40px)] p-[0_18px] border border-[var(--a-border-strong,rgba(30,41,59,0.6))] rounded-[var(--a-btn-radius,8px)] bg-[var(--a-surface-2,var(--db-surface-inner))] text-[var(--a-text-2,var(--db-text-secondary))] [font-family:inherit] text-[13px] font-semibold cursor-pointer no-underline [transition:all_var(--a-transition,_150ms_ease)]",
  "dangerButton": "inline-flex items-center justify-center gap-[6px] h-[var(--a-btn-h,38px)] rounded-[var(--a-btn-radius,9999px)] p-[0_14px] border border-[rgba(248,113,113,0.3)] rounded-[var(--a-btn-radius)] bg-[var(--a-red-subtle)] text-[var(--a-red)] text-[12px] font-bold cursor-pointer no-underline [transition:all_var(--a-transition)]",
  "addButton": "inline-flex items-center gap-[6px] h-[var(--a-btn-h)] p-[0_14px] bg-[var(--a-accent-strong)] text-[var(--a-text)] no-underline border-0 rounded-[var(--a-btn-radius)] text-[12px] font-bold [font-family:inherit] cursor-pointer [transition:all_var(--a-transition)]",
  "applyButton": "h-[var(--a-btn-h)] p-[0_14px] bg-[var(--a-surface-2)] text-[var(--a-text)] border border-[var(--a-border-strong)] rounded-[var(--a-btn-radius)] text-[12px] font-bold cursor-pointer [font-family:inherit] [transition:all_var(--a-transition)]",
  "pageButton": "inline-flex items-center gap-[6px] min-w-[26px] h-[26px] p-[0_6px] bg-transparent text-[var(--a-text-3)] border border-[transparent] rounded-[var(--a-radius-xs)] text-[11px] font-semibold no-underline [font-family:inherit] cursor-pointer [transition:all_var(--a-transition)]",
  "pageButtonActive": "bg-[var(--a-accent-strong)!important] text-[var(--a-text)!important]",
  "rowButton": "bg-[none] border-0 p-[0] text-[12px] font-bold text-[var(--a-accent)] cursor-pointer [font-family:inherit]",
  "rowButtonDelete": "text-[var(--a-red)]",
  "actionLink": "text-[12px] font-bold text-[var(--a-accent)] no-underline",
  "inputField": "h-[var(--a-input-h)] p-[0_12px] bg-[var(--a-bg)] border border-[var(--a-border-strong)] rounded-[var(--a-input-radius)] text-[var(--a-text)] [font-family:inherit] text-[12px] [outline:none] [transition:border-color_var(--a-transition),_box-shadow_var(--a-transition)] [box-sizing:border-box]",
  "searchInput": "min-w-[240px]",
  "inputFieldLg": "text-[14px] font-bold",
  "inputFieldMono": "[font-family:monospace]",
  "textareaField": "w-full min-h-[80px] p-[10px_12px] bg-[var(--a-bg)] border border-[var(--a-border-strong)] rounded-[var(--a-input-radius)] text-[var(--a-text)] [font-family:inherit] text-[12px] [resize:vertical] [outline:none] [transition:border-color_var(--a-transition),_box-shadow_var(--a-transition)]",
  "textareaFieldMd": "p-[10px_14px] text-[13px]",
  "selectField": "h-[var(--a-input-h)] p-[0_12px] bg-[var(--a-bg)] border border-[var(--a-border-strong)] rounded-[var(--a-input-radius)] text-[var(--a-text)] [font-family:inherit] text-[12px] cursor-pointer [outline:none]",
  "toolbar": "flex flex-col gap-[14px] [margin-bottom:16px]",
  "headerRow": "flex items-center justify-between gap-[14px] flex-wrap",
  "filterForm": "flex flex-wrap gap-[10px] items-center bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] p-[12px]",
  "resetLink": "inline-flex items-center gap-[6px] text-[12px] font-semibold text-[var(--a-text-3)] no-underline",
  "tableCard": "bg-[#070d18] border border-[rgba(255,255,255,0.08)] rounded-[12px] [box-shadow:0_4px_20px_rgba(0,_0,_0,_0.25)] overflow-hidden",
  "tableWrapper": "w-full overflow-x-auto",
  "table": "w-full min-w-[700px] [border-collapse:separate] [border-spacing:0] text-left text-[0.8125rem]",
  "badge": "inline-flex items-center gap-[4px] p-[3px_8px] rounded-[var(--a-badge-radius)] text-[11px] font-semibold leading-[1]",
  "badgeGreen": "bg-[var(--a-green-subtle)] text-[var(--a-green)]",
  "badgeTeal": "bg-[var(--a-accent-subtle)] text-[var(--a-accent)]",
  "badgeRed": "bg-[var(--a-red-subtle)] text-[var(--a-red)]",
  "badgeTiny": "text-[10px]",
  "pillPublished": "inline-flex p-[3px_10px] bg-[var(--a-green-subtle)] text-[var(--a-green)] border border-[rgba(52,211,153,0.35)] rounded-[var(--a-radius-pill)] text-[10px] font-bold",
  "kpiGrid": "grid [grid-template-columns:repeat(auto-fit,_minmax(180px,_1fr))] gap-[14px] [margin-bottom:20px]",
  "metricsGrid4": "grid [grid-template-columns:repeat(4,_minmax(0,_1fr))] gap-[20px] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [grid-template-columns:1fr]",
  "metricsGrid5": "grid [grid-template-columns:repeat(5,_minmax(0,_1fr))] gap-[16px] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [grid-template-columns:1fr]",
  "kpiCard": "bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-card-radius)] p-[20px] flex flex-col gap-[4px]",
  "kpiValue": "text-[var(--text-2xl)] font-bold text-[var(--a-text)]",
  "kpiLabel": "text-[11px] font-semibold uppercase tracking-[0.05em] text-[var(--a-text-4)]",
  "pagination": "flex items-center justify-between flex-wrap gap-[12px] p-[12px_16px] border-t border-[var(--a-border)] bg-[rgba(15,23,42,0.4)] text-[11px] text-[var(--a-text-3)]",
  "paginationInfo": "text-[11px] text-[var(--a-text-3)]",
  "paginationControls": "flex items-center gap-[4px]",
  "paginationSelectWrap": "flex items-center gap-[6px]",
  "paginationSelect": "h-[26px] p-[0_4px] text-[11px] bg-[var(--a-bg)] border border-[var(--a-border)] rounded-[var(--a-radius-xs)] text-[var(--a-text-2)]",
  "actionIconBtnGroup": "flex items-center gap-[6px]",
  "actionIconBtn": "inline-flex items-center justify-center w-[28px] h-[28px] rounded-[var(--a-radius-xs)] bg-[rgba(15,23,42,0.8)] border border-[var(--a-border)] text-[var(--a-text-3)] cursor-pointer [transition:all_var(--a-transition)] p-[0] no-underline",
  "actionIconBtnTeal": "text-[var(--a-accent)] [border-color:rgba(45,_212,_191,_0.3)]",
  "actionIconBtnBlue": "text-[var(--a-blue)] [border-color:rgba(96,_165,_250,_0.3)]",
  "actionIconBtnRed": "text-[var(--a-red)] [border-color:rgba(248,_113,_113,_0.3)]",
  "actionBtnDots": "flex items-center justify-center w-[26px] h-[26px] bg-transparent border border-[var(--a-border)] rounded-[var(--a-radius-xs)] text-[var(--a-text-4)] cursor-pointer",
  "viewToggleGroup": "inline-flex items-center bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] p-[2px_4px] gap-[2px]",
  "viewBtn": "flex items-center justify-center w-[28px] h-[28px] bg-transparent border-0 rounded-[var(--a-radius-xs)] text-[var(--a-text-3)] cursor-pointer",
  "viewBtnActive": "bg-[var(--a-border)] text-[var(--a-text)]",
  "backLink": "inline-flex h-[32px] items-center gap-[6px] p-[0] border-0 bg-transparent text-[var(--a-text-3)] text-[11px] font-medium no-underline [transition:color_var(--a-transition)]",
  "backLinkOverride": "h-[32px] text-[11px] bg-transparent border-0 text-[var(--a-text-3)] [padding-left:0]",
  "formStack": "flex flex-col gap-[24px]",
  "formStackCompact": "flex flex-col gap-[16px]",
  "formGrid2": "grid [grid-template-columns:repeat(2,_1fr)] gap-[14px]",
  "formGrid3": "grid [grid-template-columns:repeat(3,_1fr)] gap-[14px] [grid-template-columns:1fr]",
  "fieldGroup": "flex min-w-0 flex-col gap-[6px]",
  "fieldLabel": "block text-[var(--a-text-2)] text-[12px] font-bold",
  "fieldControl": "w-full min-h-[38px] border border-[var(--a-border-strong)] rounded-[var(--a-input-radius)] bg-[var(--a-bg)] text-[var(--a-text)] p-[8px_12px] [font:inherit] text-[13px] [outline:none] [transition:border-color_var(--a-transition),_box-shadow_var(--a-transition),_background_var(--a-transition)]",
  "formLabel": "block text-[12px] font-bold [margin-bottom:6px] text-[var(--a-text-2)]",
  "formField": "flex flex-col gap-[12px]",
  "detailLayout": "grid [grid-template-columns:minmax(0,_1fr)_minmax(250px,_280px)] gap-[14px] items-start w-full max-w-full [grid-template-columns:minmax(0,_1fr)] gap-[var(--db-space-2)]",
  "sidebarColumn": "flex flex-col gap-[14px] min-w-0 w-full max-w-full",
  "sidebarCard": "bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-card-radius)] [box-shadow:var(--a-shadow)] p-[16px] flex flex-col gap-[14px] p-[var(--db-space-2-5)] [border-color:var(--db-border)] rounded-[var(--db-radius-card)] bg-[var(--db-surface)]",
  "sidebarCardHeader": "flex items-center justify-between text-[13px] font-bold text-[var(--a-text)]",
  "sidebarHeaderTitle": "flex items-center gap-[8px]",
  "sidebarStatRow": "flex items-center justify-between text-[12px] p-[8px_0] border-b border-[rgba(30,41,59,0.6)]",
  "sidebarStatLabel": "text-[var(--a-text-3)]",
  "sidebarStatVal": "font-semibold text-[var(--a-text)]",
  "sidebarStatPercent": "text-[var(--a-green)] font-bold text-[11px]",
  "sidebarStatGroup": "flex items-center gap-[8px]",
  "sidebarHeaderLink": "text-[11px] text-[var(--a-accent)] no-underline",
  "leftColumn": "min-w-0 w-full max-w-full flex flex-col gap-[14px]",
  "sectionHeader": "p-[14px_16px] font-bold border-b border-[var(--a-border)] text-[var(--a-text)]",
  "sectionHeaderBetween": "p-[14px_16px] font-bold border-b border-[var(--a-border)] text-[var(--a-text)] flex justify-between items-center",
  "sectionTitle": "m-[0_0_8px] text-[var(--a-text)]",
  "sectionTitleLg": "m-[0_0_12px] text-[var(--a-text)]",
  "emptyStateContainer": "p-[clamp(48px,_8vw,_80px)_24px] text-center",
  "emptyStateInner": "max-w-[380px] mx-auto",
  "emptyIconWrapper": "w-[56px] h-[56px] rounded-full bg-[var(--a-surface-2)] text-[var(--a-accent)] flex items-center justify-center m-[0_auto_16px]",
  "emptyStateTitle": "m-[0_0_6px] text-[var(--text-lg)] font-bold text-[var(--a-text)]",
  "emptyStateText": "m-0 text-[13px] leading-[1.5] text-[var(--a-text-3)]",
  "sectionIconTeal": "w-[32px] h-[32px] rounded-[var(--a-radius-sm)] bg-[var(--a-accent-subtle)] border border-[rgba(45,212,191,0.25)] flex items-center justify-center text-[var(--a-accent)] shrink-0",
  "sectionIconBlue": "w-[32px] h-[32px] rounded-[var(--a-radius-sm)] bg-[var(--a-blue-subtle)] border border-[rgba(96,165,250,0.25)] flex items-center justify-center text-[var(--a-blue)] shrink-0",
  "iconTeal": "text-[var(--a-accent)]",
  "iconMuted": "text-[var(--a-text-4)]",
  "iconGreen": "text-[var(--a-green)]",
  "iconBlue": "text-[var(--a-blue)]",
  "iconRed": "text-[var(--a-red)]",
  "iconAmber": "text-[var(--a-amber)]",
  "iconSlate": "bg-[rgba(100,116,139,0.18)] text-[var(--a-text-3)]",
  "exceptionIcon": "w-[32px] h-[32px] rounded-[var(--a-radius-sm)] flex items-center justify-center shrink-0",
  "avatarBadge": "inline-flex items-center justify-center w-[24px] h-[24px] rounded-full text-[10px] font-bold text-[var(--a-text)]",
  "supplierAvatar": "flex items-center justify-center w-[28px] h-[28px] rounded-full bg-[var(--a-accent-subtle)] text-[var(--a-accent)]",
  "logoUploadBox": "relative w-[110px] h-[110px] rounded-[var(--a-radius)] border border-[1pxdashedvar(--a-border-strong)] bg-[var(--a-bg)] flex items-center justify-center overflow-hidden shrink-0",
  "logoPreviewImg": "w-full h-full [object-fit:contain]",
  "logoFileInput": "absolute [inset:0] opacity-[0] cursor-pointer",
  "activityList": "flex flex-col gap-[12px]",
  "activityItem": "flex flex-col gap-[4px] [padding-left:16px] relative",
  "activityTitle": "text-[12px] font-semibold text-[var(--a-text)]",
  "activityMeta": "text-[11px] text-[var(--a-text-4)]",
  "timelineStack": "flex flex-col gap-[10px] text-[11px]",
  "timelineEntry": "[border-left:2px_solid_var(--a-accent)] [padding-left:10px]",
  "timelineEntryMuted": "[border-left:2px_solid_var(--a-border-strong)] [padding-left:10px]",
  "timelineTitle": "text-[var(--a-text)] font-bold",
  "timelineMeta": "text-[var(--a-text-4)]",
  "commentStack": "flex flex-col gap-[12px]",
  "commentHeader": "flex justify-between items-center [margin-bottom:4px]",
  "commentTimestamp": "text-[11px] text-[var(--a-text-4)]",
  "commentBody": "m-0 text-[12px] text-[var(--a-text-2)]",
  "commentAuthor": "font-bold text-[var(--a-text)] text-[12px]",
  "chatInputWrap": "flex gap-[8px] [margin-top:8px]",
  "chatInput": "flex-1 bg-[var(--a-bg)] border border-[var(--a-border-strong)] rounded-[var(--a-radius-sm)] p-[8px_12px] text-[var(--a-text)] text-[12px]",
  "quickActionItem": "flex items-center justify-between p-[10px_12px] bg-[rgba(15,23,42,0.5)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] text-[var(--a-text-2)] text-[12px] font-medium no-underline cursor-pointer [transition:all_var(--a-transition)]",
  "formCardInner": "p-[clamp(20px,_3vw,_32px)]",
  "pForm": "p-[20px_24px]",
  "cardBorder": "p-[16px] border border-[var(--a-border)] rounded-[14px] bg-[var(--a-surface)]",
  "cardBorderStrong": "[margin-top:20px] p-[20px] border border-[var(--a-border-strong)] rounded-[14px] bg-[var(--a-surface-2)]",
  "restoreSection": "[margin-top:20px] p-[20px] border border-[var(--a-border-strong)] rounded-[14px] bg-[var(--a-surface-2)]",
  "restoreSectionTitle": "m-[0_0_8px] text-[var(--a-text)] text-[16px]",
  "restoreSectionDesc": "m-[0_0_12px] text-[var(--a-text-3)] text-[12px]",
  "mutedText": "m-0 text-[13px] text-[var(--a-text-3)]",
  "title": "m-0 [font-family:var(--font-heading,_inherit)] text-[clamp(32px,4.5vw,48px)] font-bold leading-[1.1] text-[var(--a-text)] tracking-[0]",
  "subtitle": "[margin-top:10px] [margin-bottom:0] text-[clamp(15px,1.8vw,18px)] leading-[1.5] text-[var(--a-text-3)]",
  "orderRef": "[font-family:var(--font-mono,_monospace)] font-bold text-[var(--a-text)]",
  "buyerName": "font-bold text-[var(--a-text)]",
  "schoolName": "text-[11px] text-[var(--a-text-3)] [margin-top:2px]",
  "learnerName": "text-[var(--a-text-2)]",
  "gradeText": "text-[11px] text-[var(--a-text-3)] [margin-top:2px]",
  "totalPrice": "font-bold text-[var(--a-text)]",
  "currencyText": "font-bold text-[13px]",
  "textWhiteBold": "font-bold text-[var(--a-text)]",
  "textWhiteMedium": "text-[var(--a-text)] font-medium",
  "itemCountSpan": "text-[var(--a-text)] font-semibold",
  "itemCountLabel": "text-[var(--a-text-4)] text-[11px]",
  "schoolNameSub": "text-[11px] text-[var(--a-text-4)] [margin-top:2px]",
  "emptyCell": "text-center p-[32px] text-[var(--a-text-4)]",
  "success": "m-[0_22px_16px] text-[var(--a-green)] text-[12px] font-bold",
  "error": "m-[0_22px_16px] text-[var(--a-red)] text-[12px] font-bold",
  "rowHighlight": "bg-[rgba(245,158,11,0.05)]",
  "gradePackLink": "text-[var(--a-text)] font-semibold underline [text-underline-offset:3px] text-[13px] [transition:color_var(--a-transition)]",
  "stepBtnActive": "bg-[var(--a-accent-strong)] [border-color:var(--a-accent)] text-[var(--a-text)]",
  "stepBtnDone": "bg-[var(--a-green-subtle)] [border-color:var(--a-green-border)] text-[var(--a-text)]",
  "stepBtnInactive": "bg-transparent [border-color:var(--a-border-strong)] text-[var(--a-text-3)]",
  "text-10": "text-[10px]",
  "text-11": "text-[11px]",
  "text-12": "text-[12px]",
  "text-13": "text-[13px]",
  "text-14": "text-[14px]",
  "text-15": "text-[15px]",
  "text-16": "text-[16px]",
  "text-18": "text-[18px]",
  "text-28": "text-[28px]",
  "fw-500": "font-medium",
  "fw-600": "font-semibold",
  "fw-700": "font-bold",
  "fw-800": "font-extrabold",
  "c-white": "text-[var(--a-text)]",
  "c-offwhite": "text-[var(--a-text-2)]",
  "c-soft": "text-[var(--a-text-2)]",
  "c-muted": "text-[var(--a-text-3)]",
  "c-subtle": "text-[var(--a-text-4)]",
  "c-teal": "text-[var(--a-accent)]",
  "c-green": "text-[var(--a-green)]",
  "c-blue": "text-[var(--a-blue)]",
  "c-red": "text-[var(--a-red)]",
  "c-amber": "text-[var(--a-amber)]",
  "c-success": "text-[var(--a-green)]",
  "flex": "flex",
  "flex-col": "flex flex-col",
  "flex-row": "flex flex-row",
  "flex-center": "flex items-center",
  "flex-between": "flex justify-between",
  "flex-start": "flex items-start",
  "flex-end": "flex justify-end",
  "flex-wrap": "flex-wrap",
  "items-center": "items-center",
  "itemsCenter": "items-center",
  "justify-center": "justify-center",
  "justifyCenter": "justify-center",
  "justify-between": "justify-between",
  "justify-end": "justify-end",
  "flex-1": "flex-1",
  "flex-shrink-0": "shrink-0",
  "grid-2": "grid [grid-template-columns:repeat(2,_1fr)]",
  "grid-3": "grid [grid-template-columns:repeat(3,_1fr)]",
  "grid-4": "grid [grid-template-columns:repeat(4,_1fr)]",
  "grid-6": "grid [grid-template-columns:repeat(6,_1fr)]",
  "grid-sidebar": "grid [grid-template-columns:220px_1fr] gap-[16px] items-start",
  "grid-2fr1": "grid [grid-template-columns:1.2fr_1fr] gap-[16px]",
  "grid-2equal": "grid [grid-template-columns:repeat(2,_1fr)] gap-[14px]",
  "gap-2": "gap-[2px]",
  "gap-3": "gap-[3px]",
  "gap-4": "gap-[4px]",
  "gap-6": "gap-[6px]",
  "gap-8": "gap-[8px]",
  "gap-10": "gap-[10px]",
  "gap-12": "gap-[12px]",
  "gap-14": "gap-[14px]",
  "gap-16": "gap-[16px]",
  "gap-18": "gap-[18px]",
  "gap-20": "gap-[20px]",
  "p-0": "p-[0]",
  "p-4": "p-[4px]",
  "p-6": "p-[6px]",
  "p-8": "p-[8px]",
  "p-12": "p-[12px]",
  "p-16": "p-[16px]",
  "p-20": "p-[20px]",
  "p-form": "p-[clamp(20px,_3vw,_32px)]",
  "p-card": "p-[16px]",
  "p-card-lg": "p-[18px]",
  "p-card-sm": "p-[12px]",
  "p-form-header": "p-[14px_16px]",
  "px-4": "[padding-left:4px] [padding-right:4px]",
  "px-6": "[padding-left:6px] [padding-right:6px]",
  "px-8": "[padding-left:8px] [padding-right:8px]",
  "px-10": "[padding-left:10px] [padding-right:10px]",
  "px-12": "[padding-left:12px] [padding-right:12px]",
  "py-6": "[padding-top:6px] [padding-bottom:6px]",
  "py-8": "[padding-top:8px] [padding-bottom:8px]",
  "py-12": "[padding-top:12px] [padding-bottom:12px]",
  "pt-8": "[padding-top:8px]",
  "pt-12": "[padding-top:12px]",
  "pt-20": "[padding-top:20px]",
  "pb-4": "[padding-bottom:4px]",
  "pb-6": "[padding-bottom:6px]",
  "pb-8": "[padding-bottom:8px]",
  "pb-12": "[padding-bottom:12px]",
  "pl-0": "[padding-left:0]",
  "pl-16": "[padding-left:16px]",
  "pl-12": "[padding-left:12px]",
  "pr-6": "[padding-right:6px]",
  "pr-16": "[padding-right:16px]",
  "m-0": "m-0",
  "mt-4": "[margin-top:4px]",
  "mt-6": "[margin-top:6px]",
  "mt-8": "[margin-top:8px]",
  "mt-10": "[margin-top:10px]",
  "mt-12": "[margin-top:12px]",
  "mt-14": "[margin-top:14px]",
  "mt-18": "[margin-top:18px]",
  "mt-20": "[margin-top:20px]",
  "mt-24": "[margin-top:24px]",
  "mb-2": "[margin-bottom:2px]",
  "mb-4": "[margin-bottom:4px]",
  "mb-6": "[margin-bottom:6px]",
  "mb-8": "[margin-bottom:8px]",
  "mb-10": "[margin-bottom:10px]",
  "mb-12": "[margin-bottom:12px]",
  "mb-14": "[margin-bottom:14px]",
  "mb-16": "[margin-bottom:16px]",
  "ml-6": "[margin-left:6px]",
  "ml-8": "[margin-left:8px]",
  "mr-6": "[margin-right:6px]",
  "w-full": "w-full",
  "w80": "w-[80px]",
  "w100px": "w-[100px]",
  "w40": "w-[40px]",
  "h-26": "h-[26px]",
  "h-28": "h-[28px]",
  "h-30": "h-[30px]",
  "h-34": "h-[34px]",
  "h-36": "h-[36px]",
  "h36": "h-[36px]",
  "min-w-0": "min-w-0",
  "min-w-20": "min-w-[20px]",
  "border-subtle": "border border-[var(--a-border)]",
  "border-strong": "border border-[var(--a-border-strong)]",
  "border-0": "border-0",
  "border-b": "border-b border-[var(--a-border)]",
  "border-b-subtle": "border-b border-[rgba(30,41,59,0.95)]",
  "rounded-6": "rounded-[6px]",
  "rounded-8": "rounded-[8px]",
  "rounded-12": "rounded-[12px]",
  "rounded-14": "rounded-[14px]",
  "rounded-full": "rounded-full",
  "bg-surface": "bg-[var(--a-surface)]",
  "bg-surface-deep": "bg-[var(--a-surface-2)]",
  "bg-surface-hover": "bg-[var(--a-surface-2)]",
  "bg-surface-strong": "bg-[var(--a-bg)]",
  "bg-transparent": "bg-transparent",
  "bg-card": "bg-[var(--a-surface-2)]",
  "bg-header": "bg-[rgba(15,23,42,0.6)]",
  "bg-header-solid": "bg-[var(--a-surface)]",
  "bg-teal-subtle": "bg-[var(--a-green-subtle)]",
  "bg-amber-subtle": "bg-[var(--a-amber-subtle)]",
  "uppercase": "uppercase",
  "ls-wide": "tracking-[0.05em]",
  "ls-tight": "tracking-[-0.02em]",
  "ls-none": "tracking-[-0.01em]",
  "text-center": "text-center",
  "text-left": "text-left",
  "textRight": "text-right",
  "no-underline": "no-underline",
  "underline": "underline",
  "underline-offset": "[text-underline-offset:3px]",
  "nowrap": "whitespace-nowrap",
  "h-full-btn": "w-full justify-center",
  "h-sm": "h-[34px]",
  "h-md": "h-[36px]",
  "h-lg": "h-[48px]",
  "p-sm": "p-[0_10px]",
  "p-md": "p-[0_12px]",
  "p-lg": "p-[0_14px]",
  "p16": "p-[16px]",
  "opacity-muted": "opacity-[0.7]",
  "pointer-events-none": "pointer-events-none",
  "disabled": "pointer-events-none opacity-[0.4]",
  "overflow-hidden": "overflow-hidden",
  "overflow-auto": "overflow-x-auto",
  "min-h-card": "min-h-[110px]",
  "relative": "relative",
  "absolute": "absolute",
  "accent-teal": "[accent-color:var(--a-accent)]",
  "checkbox": "w-[16px] h-[16px] [accent-color:var(--a-accent)]",
  "checkboxRed": "w-[16px] h-[16px] [accent-color:var(--a-red)]",
  "w16h16": "w-[16px] h-[16px] [accent-color:var(--a-accent)]",
  "fontMono": "[font-family:monospace]",
  "monospace": "[font-family:monospace]",
  "cursorPointer": "cursor-pointer",
  "btnSm": "p-[0_10px]",
  "headerCount": "text-[12px] font-semibold text-[var(--a-text-4)]",
  "iconBtnRed": "text-[var(--a-red)]",
  "titleAccent": "text-[22px] font-bold text-[var(--a-text)] tracking-[-0.02em]",
  "emptyStateIconWrapper": "flex items-center justify-center w-[48px] h-[48px] rounded-[12px] bg-[var(--a-accent-subtle)] text-[var(--a-accent)]",
  "btnMd": "p-[0_12px]",
  "wFullBtn": "w-full justify-center",
  "sidebarStackGap8": "gap-[8px]",
  "tableCardPadded": "p-[16px]",
  "tableCardPadded18": "p-[18px]",
  "tableCardPadded12": "p-[12px]",
  "tableLabel": "text-[10px] font-bold text-[var(--a-text-4)] uppercase [margin-bottom:8px] p-[0_8px]",
  "chartTooltip": "p-[4px_8px] text-[10px] rounded-[6px]",
  "chartLabel": "[margin-top:8px] text-[10px] text-[var(--a-text-4)]",
  "icon-inline": "inline-block [margin-right:6px]",
  "pagerRow": "flex items-center gap-[6px]",
  "sidebarGrid2": "grid [grid-template-columns:repeat(2,_1fr)] gap-[14px]",
  "sidebarFlexBetween": "flex items-center justify-between",
  "sidebarItemStack": "flex flex-col gap-[10px]",
  "sidebarItemRow": "flex items-center gap-[8px]",
  "itemNameBold": "font-bold text-[var(--a-text)] text-[14px]",
  "itemDesc": "m-[2px_0_0] text-[var(--a-text-3)] text-[12px]",
  "itemDetails": "text-[var(--a-text-3)] text-[10px]",
  "sidebarStack": "flex flex-col",
  "summaryStack": "flex flex-col",
  "iconSm": "w-[14px] h-[14px]",
  "inputFieldMuted": "text-[var(--a-text-3)]",
  "searchDropdown": "bg-[var(--a-bg)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] overflow-hidden",
  "searchDropdownItem": "p-[10px_14px] border-b border-[var(--a-border)] flex items-center justify-between cursor-pointer",
  "reportsLayout": "grid [grid-template-columns:220px_1fr] gap-[24px] items-start",
  "reportsCatLabel": "text-[10px] font-bold text-[var(--a-text-4)] uppercase [margin-bottom:8px] p-[0_8px]",
  "reportsCatMenu": "flex flex-col gap-[4px]",
  "reportsCatBtn": "flex items-center gap-[10px] p-[8px_12px] rounded-[var(--a-radius-sm)] bg-transparent text-[var(--a-text-3)] border border-[transparent] text-[12px] font-medium cursor-pointer text-left",
  "reportsCatBtnActive": "bg-[var(--a-accent-subtle)] text-[var(--a-accent)] border border-[rgba(45,212,191,0.4)] font-semibold",
  "reportsContent": "flex flex-col gap-[28px]",
  "reportsGrid": "grid [grid-template-columns:1.2fr_1fr] gap-[24px]",
  "reportsChartHeader": "flex justify-between items-center [margin-bottom:14px]",
  "reportsChartTitle": "text-[var(--a-text)] text-[14px]",
  "reportsChartSelect": "h-[28px] text-[11px]",
  "reportsChartArea": "relative h-[160px] flex items-center justify-center",
  "reportsChartTooltip": "absolute [top:0] [right:80px] bg-[var(--a-bg)] border border-[var(--a-accent)] rounded-[6px] p-[4px_8px] text-[10px]",
  "reportsChartTooltipLabel": "text-[var(--a-text-3)]",
  "reportsChartTooltipValue": "text-[var(--a-text)]",
  "reportsChartFooter": "flex justify-between text-[10px] text-[var(--a-text-4)] [margin-top:8px]",
  "reportsListTitle": "text-[var(--a-text)] text-[14px] [margin-bottom:14px]",
  "reportsList": "flex flex-col gap-[10px] [margin-top:10px]",
  "reportsListItem": "flex justify-between items-center text-[12px] border-b border-[var(--a-border)] [padding-bottom:6px]",
  "reportsRank": "text-[var(--a-accent)] font-bold",
  "reportsSchoolName": "text-[var(--a-text)]",
  "reportsSchoolValue": "text-[var(--a-green)]",
  "settingsTabBar": "flex flex-wrap gap-[8px] border-b border-[var(--a-border)] [padding-bottom:12px] [margin-bottom:20px]",
  "settingsTabBtn": "h-[44px] min-h-[44px] p-[0_18px] text-[13px] font-bold justify-center",
  "settingsTabBtnActive": "bg-[var(--a-accent-strong)] [border-color:var(--a-accent)] text-[var(--a-text)]",
  "settingsTabBtnInactive": "bg-[var(--a-surface)] [border-color:var(--a-border)] text-[var(--a-text-3)]",
  "setIconTeal": "text-[var(--a-accent)]",
  "setIconBlue": "text-[var(--a-blue)]",
  "setIconAmber": "text-[var(--a-amber)]",
  "setIconGreen": "text-[var(--a-green)]",
  "settingsGrid2": "grid [grid-template-columns:repeat(2,_1fr)] gap-[20px]",
  "settingsGrid3": "grid [grid-template-columns:repeat(3,_1fr)] gap-[20px]",
  "permGrid3": "grid [grid-template-columns:repeat(3,_1fr)] gap-[20px] text-[12px]",
  "settingsCheckbox": "[accent-color:var(--a-accent-strong)] w-[16px] h-[16px]",
  "prefRow": "flex justify-between items-center text-[12px]",
  "prefLabel": "text-[var(--a-text-2)]",
  "userSectionTitle": "m-0 text-[16px] font-bold text-[var(--a-text)]",
  "tableUserName": "text-[var(--a-text)]",
  "tablePerms": "text-[11px] text-[var(--a-text-2)]",
  "permGroupTitle": "text-[var(--a-text)] block [margin-bottom:8px]",
  "checkboxStack": "flex flex-col gap-[6px]",
  "templateCard": "bg-[var(--a-bg)] border border-[var(--a-border-strong)] rounded-[var(--a-radius-sm)] p-[14px]",
  "templateCardHead": "flex justify-between items-center [margin-bottom:6px]",
  "templateCardTitle": "text-[var(--a-text)] text-[13px]",
  "templateCardDesc": "m-[0_0_10px] text-[11px] text-[var(--a-text-3)]",
  "templateEditBtn": "h-[28px] text-[11px]",
  "brandAssetBox": "bg-[var(--a-bg)] border border-[1pxdashedvar(--a-border-strong)] rounded-[var(--a-radius-sm)] p-[14px] text-center",
  "brandAssetTitle": "text-[var(--a-text)] text-[12px] block [margin-bottom:4px]",
  "brandAssetSub": "text-[11px] text-[var(--a-text-4)]",
  "settingsCentered": "m-0 p-[12px] text-[var(--a-text-3)] text-[12px] text-center",
  "settingsStatusGrid": "grid gap-[14px]",
  "settingsStatusCard": "flex items-center justify-between p-[16px] border border-[var(--a-border)] rounded-[12px] bg-[var(--a-surface)]",
  "settingsStatusCardTitle": "m-[8px_0_4px] text-[var(--a-text)] text-[16px]",
  "settingsStatusCardCaption": "m-0 text-[var(--a-text-3)] text-[12px]",
  "settingsStatusCardPurpose": "m-[2px_0_0] text-[var(--a-text-3)] text-[12px]",
  "settingsExportBtns": "flex gap-[14px]",
  "settingsRestoreSection": "[margin-top:20px] p-[20px] border border-[var(--a-border-strong)] rounded-[14px] bg-[var(--a-surface-2)]",
  "settingsRestoreTitle": "m-[0_0_8px] text-[var(--a-text)]",
  "settingsRestoreDesc": "m-[0_0_12px] text-[var(--a-text-3)] text-[12px]",
  "settingsRestoreActions": "flex gap-[12px] [margin-top:12px]",
  "settingsLogKey": "text-[var(--a-green)]",
  "settingsLogEmpty": "text-center text-[var(--a-text-3)] p-[20px]",
  "settingsIconCheck": "w-[14px] h-[14px]",
  "settingsExportIcon": "w-[16px] h-[16px] inline-block [margin-right:6px]",
  "occLegendLink": "inline-flex items-center gap-[4px] text-[12px] text-[var(--a-accent)] no-underline font-semibold",
  "occStatusRow": "flex items-center gap-[6px]",
  "occCardTitle": "text-[var(--a-text)]",
  "occMetaRow": "flex items-center gap-[10px]",
  "occDetailGrid": "grid [grid-template-columns:1fr_1fr] gap-[8px] [margin-top:4px]",
  "occDetailCell": "bg-[var(--a-surface-2)] p-[8px_10px] rounded-[6px]",
  "occDetailLabel": "text-[10px] text-[var(--a-text-3)]",
  "occDetailValue": "text-[15px] font-bold text-[var(--a-text)]",
  "occDetailValueRed": "text-[15px] font-bold text-[var(--a-red)]",
  "occSupplierInfo": "flex flex-col gap-[10px] [margin-top:6px] text-[12px]",
  "occSupplierRow": "flex justify-between",
  "occSupplierLabel": "text-[var(--a-text-3)]",
  "occSupplierVal": "text-[var(--a-text)]",
  "occSupplierValGreen": "text-[var(--a-green)]",
  "occSupplierValLight": "text-[var(--a-text-2)]",
  "occHealthGreen": "text-[var(--a-green)]",
  "occHealthRed": "text-[var(--a-red)]",
  "occScoreBig": "text-[var(--a-accent)] text-[16px]",
  "occBadgePadded": "p-[4px_8px] text-[11px]",
  "occAlignEnd": "[align-self:flex-end]",
  "kanbanGrid": "grid [grid-template-columns:repeat(4,_minmax(220px,_1fr))] gap-[14px] [margin-top:12px] [grid-template-columns:repeat(2,_1fr)] [grid-template-columns:1fr]",
  "kanbanCol": "min-h-[380px]",
  "kanbanItems": "flex flex-col gap-[10px]",
  "kanbanCard": "flex-col items-start gap-[6px] overflow-hidden",
  "kanbanCardTop": "flex justify-between items-center w-full gap-[8px] min-w-0",
  "kanbanPoNumber": "text-[var(--a-text)] text-[13px] whitespace-nowrap overflow-hidden [text-overflow:ellipsis] min-w-0",
  "kanbanValue": "text-[var(--a-accent)] font-bold whitespace-nowrap shrink-0",
  "kanbanMeta": "text-[11px] text-[var(--a-text-3)] whitespace-nowrap overflow-hidden [text-overflow:ellipsis] max-w-full",
  "kanbanAdvance": "h-[24px] text-[10px] [align-self:flex-end] [margin-top:4px]",
  "pageShowSelect": "bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[6px] text-[var(--a-text-2)] text-[11px] p-[3px_6px] cursor-pointer",
  "poBtnSmall": "h-[26px] text-[10px]",
  "kanbanMetricCaption": "text-[11px] text-[var(--a-text-4)]",
  "kanbanMetricValueAmber": "text-[var(--a-amber)]",
  "kanbanMetricValueRed": "text-[var(--a-red)]",
  "legendDotInline": "inline-block w-[10px] h-[10px] rounded-full [margin-right:6px] [vertical-align:middle]",
  "dataTable": "w-full min-w-[700px] [border-collapse:separate] [border-spacing:0] text-[0.8125rem] text-left",
  "datePickerBtn": "inline-flex items-center gap-[8px] p-[8px_14px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[8px] text-[var(--a-text-2)] text-[12px] font-semibold cursor-pointer [transition:border-color_140ms_ease,_background_140ms_ease]",
  "exceptionDetails": "flex flex-col min-w-0",
  "exceptionHeadline": "text-[12px] font-semibold text-[var(--a-text)] whitespace-nowrap overflow-hidden [text-overflow:ellipsis]",
  "exceptionItem": "flex items-center justify-between gap-[12px] p-[11px_14px] bg-[var(--a-surface-2)] border border-[var(--a-border)] rounded-[8px] cursor-pointer [transition:all_140ms_ease]",
  "exceptionLeft": "flex items-center gap-[12px] min-w-0",
  "exceptionList": "flex flex-col gap-[10px] [margin-top:4px]",
  "exceptionRight": "flex items-center gap-[10px] shrink-0",
  "exceptionSubtext": "text-[11px] text-[var(--a-text-3)] whitespace-nowrap overflow-hidden [text-overflow:ellipsis]",
  "exceptionTime": "text-[11px] text-[var(--a-text-4)] min-w-[44px] text-right",
  "filterSelect": "inline-flex items-center gap-[6px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[8px] text-[var(--a-text-2)] text-[12px] p-[7px_12px] cursor-pointer",
  "kpiCardActive": "[border-color:rgba(45,_212,_191,_0.6)_!important] [box-shadow:0_0_0_1px_rgba(45,_212,_191,_0.4),_0_8px_24px_rgba(0,_0,_0,_0.35)]",
  "kpiFooter": "flex items-end justify-between [margin-top:10px] gap-[8px]",
  "kpiHeaderInfo": "flex flex-col min-w-0",
  "kpiIconAmber": "bg-[rgba(245,158,11,0.15)] text-[var(--a-amber)]",
  "kpiIconBlue": "bg-[rgba(59,130,246,0.15)] text-[var(--a-blue)]",
  "kpiIconCyan": "bg-[rgba(6,182,212,0.15)] text-[#06b6d4]",
  "kpiIconEmerald": "bg-[rgba(16,185,129,0.15)] text-[var(--a-accent)]",
  "kpiIconTeal": "bg-[rgba(45,212,191,0.15)] text-[var(--a-accent)]",
  "kpiIconSlate": "bg-[rgba(148,163,184,0.15)] text-[var(--db-text-muted)]",
  "kpiIconWrapper": "flex items-center justify-center w-[36px] h-[36px] rounded-full shrink-0",
  "kpiSparkline": "w-[72px] h-[24px] shrink-0",
  "kpiTop": "flex items-center gap-[10px]",
  "kpiTrend": "inline-flex items-center gap-[3px] text-[11px] font-semibold whitespace-nowrap",
  "kpiTrendDown": "text-[var(--a-red)]",
  "kpiTrendUp": "text-[var(--a-accent)]",
  "panel": "flex flex-col bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[12px] p-[18px_20px] [box-shadow:0_4px_16px_rgba(0,_0,_0,_0.25)]",
  "panelHeader": "flex items-center justify-between gap-[12px] [margin-bottom:14px]",
  "panelTitle": "m-0 text-[15px] font-bold text-[var(--a-text)]",
  "severityBadge": "inline-flex items-center justify-center p-[2px_8px] text-[10px] font-bold rounded-full capitalize tracking-[0.02em]",
  "severityHigh": "bg-[rgba(239,68,68,0.18)] text-[var(--a-red)] border border-[rgba(239,68,68,0.35)]",
  "severityInfo": "bg-[rgba(59,130,246,0.18)] text-[var(--a-blue)] border border-[rgba(59,130,246,0.35)]",
  "severityLow": "bg-[rgba(16,185,129,0.18)] text-[var(--a-green)] border border-[rgba(16,185,129,0.35)]",
  "severityMedium": "bg-[rgba(245,158,11,0.18)] text-[var(--a-amber)] border border-[rgba(245,158,11,0.35)]",
  "m0": "m-0",
  "mt4": "[margin-top:4px]",
  "mt6": "[margin-top:6px]",
  "mt8": "[margin-top:8px]",
  "mt12": "[margin-top:12px]",
  "mt16": "[margin-top:16px]",
  "mt18": "[margin-top:18px]",
  "mt20": "[margin-top:20px]",
  "mt24": "[margin-top:24px]",
  "mb4": "[margin-bottom:4px]",
  "mb6": "[margin-bottom:6px]",
  "mb8": "[margin-bottom:8px]",
  "mb12": "[margin-bottom:12px]",
  "ml6": "[margin-left:6px]",
  "ml8": "[margin-left:8px]",
  "pt8": "[padding-top:8px]",
  "pt12": "[padding-top:12px]",
  "gap4": "gap-[4px]",
  "gap6": "gap-[6px]",
  "gap8": "gap-[8px]",
  "gap10": "gap-[10px]",
  "gap14": "gap-[14px]",
  "gap16": "gap-[16px]",
  "fw700": "font-bold",
  "text14": "text-[14px]",
  "text18": "text-[18px]",
  "cWhite": "text-[var(--a-text)]",
  "noWrap": "whitespace-nowrap",
  "cMuted": "text-[var(--a-text-3)]",
  "cSubtle": "text-[var(--a-text-4)]",
  "cTeal": "text-[var(--a-accent)]",
  "cGreen": "text-[var(--a-green)]",
  "cRed": "text-[var(--a-red)]",
  "cAmber": "text-[var(--a-amber)]",
  "gap18": "gap-[18px]",
  "justifyEnd": "justify-end",
  "fw600": "font-semibold",
  "lsWide": "tracking-[0.05em]",
  "pt10": "[padding-top:10px]",
  "text8": "text-[8px]",
  "text12": "text-[12px]",
  "text13": "text-[13px]",
  "text15": "text-[15px]",
  "grid2": "grid [grid-template-columns:repeat(2,_1fr)]",
  "grid2equal": "grid [grid-template-columns:repeat(2,_1fr)] gap-[14px]",
  "grid6": "grid [grid-template-columns:repeat(6,_1fr)]",
  "p12": "p-[12px]",
  "pCard": "p-[16px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-card-radius)]",
  "borderB": "border-b border-[var(--a-border)]",
  "borderT": "border-t border-[var(--a-border)]",
  "textCenter": "text-center",
  "h28": "h-[28px]",
  "h34": "h-[34px]",
  "hFullBtn": "h-full",
  "wFull": "w-full",
  "button": "inline-flex items-center gap-[6px] p-[0_14px] h-[32px] border border-[var(--a-border)] rounded-[var(--a-radius)] bg-[var(--a-surface)] text-[var(--a-text)] text-[12px] font-bold [font-family:inherit] cursor-pointer [transition:border-color_var(--a-transition),_background_var(--a-transition)]",
  "field": "flex flex-col gap-[6px]",
  "formGrid": "grid [grid-template-columns:repeat(2,_1fr)] gap-[14px]",
  "formPanel": "flex flex-col gap-[18px] p-[clamp(20px,_3vw,_32px)] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-card-radius)]",
  "inlineForm": "flex items-end gap-[10px]",
  "muted": "text-[var(--a-text-3)] text-[12px]",
  "page": "w-full max-w-full [margin-inline:auto]",
  "wide": "w-full",
  "mono": "[font-family:monospace]",
  "header": "text-[13px] font-bold text-[var(--a-text)]",
  "actions": "flex items-center gap-[8px]",
  "pageNav": "flex items-center gap-[6px]",
  "block": "block",
  "statusBadge": "inline-flex items-center gap-[5px] p-[2px_8px] rounded-[var(--a-badge-radius)] text-[11px] font-semibold whitespace-nowrap border border-[transparent]",
  "statusBadgeDot": "w-[6px] h-[6px] rounded-full shrink-0 bg-[var(--a-green)] bg-[var(--a-amber)] bg-[var(--a-red)] bg-[var(--a-blue)]",
  "statusActive": "bg-[var(--a-green-subtle)] text-[var(--a-green)] [border-color:var(--a-green-border)]",
  "statusPending": "bg-[var(--a-amber-subtle)] text-[var(--a-amber)] [border-color:var(--a-amber-border)]",
  "statusCritical": "bg-[var(--a-red-subtle)] text-[var(--a-red)] [border-color:var(--a-red-border)]",
  "statusInfo": "bg-[var(--a-blue-subtle)] text-[var(--a-blue)] [border-color:var(--a-blue-border)]",
  "kanbanGridFixed": "grid [grid-template-columns:repeat(3,_minmax(260px,_1fr))] gap-[16px] items-start [grid-template-columns:1fr]",
  "kanbanColHeader": "flex items-center justify-between [margin-bottom:10px] p-[0_2px]",
  "kanbanColTitle": "flex items-center gap-[8px] text-[12px] font-bold text-[var(--a-text-2)] uppercase tracking-[0.05em]",
  "kanbanColCount": "flex items-center justify-center min-w-[20px] h-[20px] p-[0_6px] rounded-[var(--a-radius-pill)] bg-[var(--a-surface-3)] text-[var(--a-text-4)] text-[10px] font-bold",
  "kanbanCardFixed": "flex flex-col gap-[8px] p-[14px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] [transition:border-color_var(--a-transition)]",
  "kanbanCardTitle": "text-[13px] font-semibold text-[var(--a-text)] leading-[1.3] overflow-hidden [text-overflow:ellipsis] whitespace-nowrap max-w-full",
  "kanbanCardMeta": "flex items-center gap-[12px] text-[11px] text-[var(--a-text-4)] flex-nowrap",
  "kanbanCardMetaItem": "flex items-center gap-[4px] whitespace-nowrap overflow-hidden [text-overflow:ellipsis]",
  "kanbanCardAvatar": "flex items-center justify-center w-[24px] h-[24px] rounded-full bg-[var(--a-accent-subtle)] text-[var(--a-accent)] text-[10px] font-bold shrink-0",
  "tableContainerFixed": "bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius)] overflow-hidden",
  "tableInnerScroll": "w-full overflow-x-auto [scrollbar-width:thin] [scrollbar-color:var(--a-border)_transparent]",
  "tableFixed": "w-full min-w-[800px] [border-collapse:separate] [border-spacing:0] text-[0.8125rem]",
  "tableColName": "min-w-[160px]",
  "tableColAmount": "min-w-[100px] text-right",
  "tableColStatus": "min-w-[100px]",
  "tableColActions": "min-w-[120px] text-right",
  "kpiRowGrid": "grid [grid-template-columns:repeat(4,_1fr)] gap-[14px] [grid-template-columns:repeat(2,_1fr)] [grid-template-columns:1fr]",
  "kpiCardFixed": "flex flex-col gap-[6px] p-[16px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius-sm)] min-h-[90px]",
  "kpiCardTop": "flex items-center justify-between [margin-bottom:2px]",
  "kpiCardLabel": "text-[11px] font-semibold text-[var(--a-text-3)] uppercase tracking-[0.04em]",
  "kpiCardIcon": "flex items-center justify-center w-[32px] h-[32px] rounded-[var(--a-radius-xs)] shrink-0",
  "kpiCardValue": "text-[22px] font-bold text-[var(--a-text)] leading-[1.1]",
  "kpiCardCaption": "text-[11px] text-[var(--a-text-4)]",
  "detailBodyGrid": "grid [grid-template-columns:1fr_280px] gap-[16px] items-start [grid-template-columns:1fr]",
  "detailBodyMain": "flex flex-col gap-[16px] min-w-0",
  "formGrid3Col": "grid [grid-template-columns:repeat(3,_1fr)] gap-[14px] [grid-template-columns:repeat(2,_1fr)] [grid-template-columns:1fr]",
  "formGrid3ColFull": "[grid-column:1_/_-1]",
  "formSectionCard": "flex flex-col gap-[16px] p-[20px] bg-[var(--a-surface)] border border-[var(--a-border)] rounded-[var(--a-radius)]",
  "formSectionHeader": "flex items-center gap-[10px] [margin-bottom:4px]",
  "formSectionIcon": "flex items-center justify-center w-[32px] h-[32px] rounded-[var(--a-radius-xs)] shrink-0",
  "formFieldGroup": "flex flex-col gap-[6px] w-full min-w-0",
  "formFieldLabel": "text-[12px] font-semibold text-[var(--a-text-3)]",
  "formFieldInput": "w-full h-[var(--a-input-h)] p-[0_12px] bg-[var(--a-surface-2)] border border-[var(--a-border)] rounded-[var(--a-input-radius)] text-[var(--a-text)] text-[13px] [font-family:inherit] [outline:none] [transition:border-color_var(--a-transition)] w-full max-w-full bg-[var(--db-surface-inner)] [border-color:var(--db-border)] rounded-[var(--db-radius-control)] text-[var(--db-text-primary)]",
  "formFieldHelper": "text-[11px] text-[var(--a-text-4)]",
  "toolbarFixed": "flex items-center justify-between flex-wrap gap-[12px] p-[12px_0]",
  "toolbarLeft": "flex items-center gap-[10px]",
  "toolbarRight": "flex items-center gap-[8px]"
};

export const adminStyles: AdminStylesDictionary = new Proxy(rawStyles, {
  get(target, prop: string) {
    if (prop in target) {
      return target[prop];
    }
    // Return empty string fallback for any unspecified utility modifier
    return "";
  },
});

export default adminStyles;
