/**
 * Quotations Tailwind styles mapping.
 * Replaces the retired Quotations.module.css with pure Tailwind CSS classes.
 */
export const quotationStyles: Record<string, string> = {
  container: "flex flex-col gap-5 w-full max-w-7xl mx-auto py-2 pb-10 text-[var(--db-text-primary,#ffffff)]",
  headerRow: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 flex-wrap pb-2",
  pageTitle: "m-0 text-xl sm:text-2xl font-extrabold text-white tracking-tight",
  pageSubtitle: "m-0 text-xs sm:text-sm text-slate-400",
  backButton:
    "inline-flex items-center gap-2 px-3 py-1.5 bg-[var(--db-surface-inner,#090e17)] border border-[var(--db-border,#1e293b)] rounded-lg text-slate-400 text-xs font-semibold hover:border-slate-700 hover:text-white transition-all w-fit no-underline",
  preparedByArea: "flex flex-col gap-1 min-w-[200px]",
  topGrid: "grid grid-cols-1 lg:grid-cols-2 gap-5 items-start",
  bottomGrid: "grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-5 items-start",
  card: "p-5 rounded-xl border border-[var(--db-border,#1e293b)] bg-[var(--db-surface,#0c1322)] shadow-sm flex flex-col gap-4",
  cardHeader: "flex items-center justify-between pb-3 border-b border-[var(--db-border,#1e293b)]",
  cardTitle: "text-sm sm:text-base font-bold text-white tracking-tight m-0 flex items-center gap-2",
  cardIcon: "text-emerald-500",
  clientTypeToggle: "inline-flex items-center p-0.5 bg-[var(--db-surface-inner,#090e17)] border border-[var(--db-border,#1e293b)] rounded-lg gap-1",
  clientTypeBtn:
    "px-3 py-1 rounded-md text-xs font-semibold text-slate-400 hover:text-white transition-colors cursor-pointer border-0 bg-transparent",
  clientTypeBtnActive:
    "bg-emerald-500 text-slate-950 font-bold hover:text-slate-950 shadow-xs",
  formGroup: "flex flex-col gap-1.5",
  formRow2: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  formLabel: "text-xs font-semibold text-slate-300",
  inputLabel: "text-xs font-semibold text-slate-300",
  schoolSearchWrapper: "relative w-full",
  schoolDropdown:
    "absolute top-[calc(100%+4px)] left-0 right-0 z-50 max-h-60 overflow-y-auto rounded-lg bg-[var(--db-surface-inner,#090e17)] border border-[var(--db-border,#1e293b)] shadow-2xl divide-y divide-[var(--db-border,#1e293b)]",
  schoolOptionBtn:
    "w-full text-left p-2.5 hover:bg-slate-800/60 cursor-pointer flex flex-col gap-0.5 transition-colors border-0 bg-transparent text-slate-200",
  schoolOptionName: "text-xs font-bold text-white",
  schoolOptionMeta: "text-[11px] text-slate-400",
  schoolDropdownLoading: "p-3 text-xs text-slate-400 text-center",
  schoolDropdownEmpty: "p-3 text-xs text-slate-400 text-center",
  tableWrapper: "w-full overflow-x-auto rounded-lg border border-[var(--db-border,#1e293b)]",
  tableScroll: "w-full overflow-x-auto",
  itemsTable: "w-full border-collapse text-xs text-slate-200",
  itemSkuHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-left border-b border-[var(--db-border,#1e293b)]",
  itemDescriptionHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-left border-b border-[var(--db-border,#1e293b)]",
  itemUnitHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-left border-b border-[var(--db-border,#1e293b)]",
  itemQtyHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-center border-b border-[var(--db-border,#1e293b)]",
  itemPriceHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-right border-b border-[var(--db-border,#1e293b)]",
  itemTotalHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-right border-b border-[var(--db-border,#1e293b)]",
  itemActionHeader: "px-3 py-2.5 bg-[var(--db-surface-inner,#090e17)] text-[11px] font-bold text-slate-400 uppercase tracking-wider text-center border-b border-[var(--db-border,#1e293b)]",
  relativeCell: "relative p-1 align-middle border-b border-[var(--db-border,#1e293b)]",
  actionCell: "p-1 text-center align-middle border-b border-[var(--db-border,#1e293b)]",
  totalCell: "p-2.5 text-right font-bold tabular-nums text-emerald-400 align-middle border-b border-[var(--db-border,#1e293b)]",
  tableInput:
    "w-full h-8 px-2 text-xs rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700/60 text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500",
  tableInputCenter:
    "w-full h-8 px-2 text-xs text-center rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700/60 text-white focus:outline-none focus:border-emerald-500",
  tableInputRight:
    "w-full h-8 px-2 text-xs text-right tabular-nums rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700/60 text-white focus:outline-none focus:border-emerald-500",
  deleteRowBtn:
    "p-1.5 rounded text-slate-500 hover:text-rose-400 hover:bg-rose-950/40 transition-colors cursor-pointer border-0 bg-transparent",
  itemAutocomplete:
    "absolute top-full left-0 right-0 z-50 max-h-52 overflow-y-auto rounded-lg bg-[var(--db-surface-inner,#090e17)] border border-slate-700 shadow-2xl divide-y divide-slate-800",
  itemAutocompleteOption:
    "w-full text-left p-2 hover:bg-slate-800/60 cursor-pointer flex justify-between items-center gap-2 border-0 bg-transparent text-slate-200",
  itemOptionTitle: "text-xs font-semibold text-white",
  itemOptionMeta: "text-[10px] text-slate-400",
  itemOptionDetail: "flex flex-col gap-0.5",
  itemOptionPrice: "text-xs font-bold text-emerald-400 tabular-nums shrink-0",
  itemAutocompleteLoading: "p-2.5 text-xs text-slate-400 text-center",
  itemAutocompleteEmpty: "p-2.5 text-xs text-slate-400 text-center",
  summaryCard:
    "p-5 rounded-xl border border-[var(--db-border,#1e293b)] bg-[var(--db-surface,#0c1322)] flex flex-col gap-3 shadow-sm",
  summaryTitle: "text-sm font-bold text-white m-0 pb-2 border-b border-[var(--db-border,#1e293b)]",
  summaryList: "flex flex-col gap-2",
  summaryRow: "flex justify-between items-center text-xs text-slate-400",
  summaryLabel: "flex items-center gap-1.5",
  summaryLabelIcon: "text-slate-500",
  summaryValue: "text-xs font-semibold text-slate-200 tabular-nums",
  summaryDivider: "h-px bg-[var(--db-border,#1e293b)] my-1",
  summaryAdjustmentRow: "flex justify-between items-center text-xs gap-2",
  summaryAdjInput:
    "w-20 h-7 px-2 text-right text-xs rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700 text-white tabular-nums focus:outline-none focus:border-emerald-500",
  discountValue: "text-rose-400 font-semibold tabular-nums",
  summaryVatToggleRow: "flex justify-between items-center text-xs text-slate-400 py-1",
  summaryRowGrand:
    "flex justify-between items-center pt-2 border-t border-[var(--db-border,#1e293b)]",
  grandTotalLabel: "text-sm font-bold text-white",
  grandTotalAmount: "text-lg sm:text-xl font-extrabold text-emerald-400 tabular-nums",
  summaryActions: "flex flex-col gap-2 pt-2",
  errorBanner:
    "p-3 rounded-lg bg-rose-950/40 border border-rose-800 text-xs text-rose-300",
  successBanner:
    "p-3 rounded-lg bg-emerald-950/40 border border-emerald-800 text-xs text-emerald-300",
  checkboxControl: "flex items-center gap-2",
  checkboxLabel: "text-xs font-medium text-slate-300 cursor-pointer flex items-center gap-2",
  csvTextarea:
    "w-full h-24 p-2 text-xs font-mono rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700 text-white focus:outline-none focus:border-emerald-500 resize-none",
  spinIcon: "animate-spin text-slate-400",
  statusSelect:
    "h-8 px-2 text-xs rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700 text-white focus:outline-none",
  textMuted: "text-slate-400 text-xs",
  convertLink: "text-emerald-400 hover:underline text-xs font-semibold inline-flex items-center gap-1",
  convertLinkInline: "text-emerald-400 hover:underline text-xs font-semibold",
  convertedLinkWrap: "p-3 rounded-lg bg-emerald-950/20 border border-emerald-800/40 flex items-center gap-2 text-xs text-emerald-300",
  detailStack: "flex flex-col gap-5",
  detailHeaderRow: "flex justify-between items-start gap-4 flex-wrap pb-2",
  detailTitleRow: "flex flex-col gap-1",
  detailActions: "flex items-center gap-2 flex-wrap",
  infoStack: "flex flex-col gap-2",
  infoLabel: "text-xs text-slate-400",
  infoValue: "text-xs font-semibold text-slate-200",
  infoMeta: "text-[11px] text-slate-500",
  detailTable: "w-full border-collapse text-xs text-slate-200",
  detailTableRow: "border-b border-[var(--db-border,#1e293b)] hover:bg-slate-800/30",
  detailCell: "p-3 align-middle",
  detailCellSku: "p-3 font-mono text-slate-400 align-middle",
  detailCellCenter: "p-3 text-center align-middle",
  detailCellTotal: "p-3 text-right font-bold text-emerald-400 tabular-nums align-middle",
  bankingBox: "p-4 rounded-lg bg-[var(--db-surface-inner,#090e17)] border border-[var(--db-border,#1e293b)] flex flex-col gap-1 text-xs",
  bankingText: "text-slate-300",
  bankingTextBold: "text-white font-bold",
  notesContainer: "flex flex-col gap-2",
  notesText: "text-xs text-slate-300 leading-relaxed whitespace-pre-wrap",
  packList: "flex flex-col gap-1.5",
  packListItem: "flex justify-between items-center p-2 rounded bg-[var(--db-surface-inner,#090e17)] text-xs",
  packItemTitle: "font-semibold text-slate-200",
  packItemPrice: "font-mono text-emerald-400",
  templateChip: "px-2 py-0.5 rounded-full text-[11px] font-semibold bg-slate-800 text-slate-300 border border-slate-700",
  modalOverlay: "fixed inset-0 bg-black/70 backdrop-blur-xs z-50 flex items-center justify-center p-4",
  modalContent: "w-full max-w-lg rounded-xl bg-[var(--db-surface,#0c1322)] border border-[var(--db-border,#1e293b)] shadow-2xl p-5 flex flex-col gap-4",
  modalHeader: "flex justify-between items-start pb-3 border-b border-[var(--db-border,#1e293b)]",
  modalTitle: "text-base font-bold text-white m-0",
  modalSubtitle: "text-xs text-slate-400 m-0",
  modalCloseBtn: "p-1 rounded text-slate-400 hover:text-white border-0 bg-transparent cursor-pointer",
  modalBody: "flex flex-col gap-3",
  modalFieldSpaced: "flex flex-col gap-1.5",
  modalSelect: "w-full h-9 px-3 text-xs rounded bg-[var(--db-surface-inner,#090e17)] border border-slate-700 text-white focus:outline-none focus:border-emerald-500",
  modalFooterActions: "flex justify-end gap-2 pt-3 border-t border-[var(--db-border,#1e293b)]",
  modalLoading: "p-6 text-center text-xs text-slate-400",
  modalEmpty: "p-6 text-center text-xs text-slate-400",
};

export default quotationStyles;
